name: npm
on:
  push:
    branches: [main]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npx pleb@8 publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
